"""Ichki lug'at: fan, fakultet, yo'nalish va boshqa atamalarning rasmiy ruscha va inglizcha nomlari.

Kalit — o'zbekcha nom (rim raqami va «(c)» kabi belgilarsiz: «Fransuz tili I» → «Fransuz tili»). Lug'atda yo'q
nomlarni kurs koordinatori /tarjimalar orqali o'zi kiritadi (ular ushbu lug'atdan ustun turadi).
"""

TERMS: dict[str, tuple[str, str]] = {
    # --- universitet, fakultetlar, yo'nalishlar
    "Jahon iqtisodiyoti va diplomatiya universiteti": ("Университет мировой экономики и дипломатии",
                                                       "University of World Economy and Diplomacy"),
    "Xalqaro munosabatlar": ("Международные отношения", "International Relations"),
    "Siyosatshunoslik": ("Политология", "Political Science"),
    "Xalqaro huquq": ("Международное право", "International Law"),
    "Xalqaro iqtisodiy munosabatlar": ("Международные экономические отношения", "International Economic Relations"),
    "Xalqaro iqtisodiyot va menejment": ("Международная экономика и менеджмент", "International Economics and Management"),
    "Jahon iqtisodiyoti": ("Мировая экономика", "World Economy"),
    "Xalqaro jurnalistika": ("Международная журналистика", "International Journalism"),
    "Jurnalistika": ("Журналистика", "Journalism"),
    "Huquqshunoslik": ("Юриспруденция", "Law"),
    "Iqtisodiyot": ("Экономика", "Economics"),
    "Menejment": ("Менеджмент", "Management"),
    "Mintaqashunoslik": ("Регионоведение", "Regional Studies"),
    "Xalqaro biznes": ("Международный бизнес", "International Business"),
    "Namunaviy fakultet": ("Демонстрационный факультет", "Demo Faculty"),
    # --- xalqaro munosabatlar va siyosat fanlari
    "Xalqaro tashkilotlar": ("Международные организации", "International Organizations"),
    "Xalqaro munosabatlar nazariyasi": ("Теория международных отношений", "Theory of International Relations"),
    "Xalqaro munosabatlar tarixi": ("История международных отношений", "History of International Relations"),
    "Xalqaro munosabatlarga kirish": ("Введение в международные отношения", "Introduction to International Relations"),
    "Siyosat va OAV": ("Политика и СМИ", "Politics and the Media"),
    "Siyosat va ommaviy axborot vositalari": ("Политика и средства массовой информации", "Politics and the Mass Media"),
    "Siyosiy nazariya": ("Политическая теория", "Political Theory"),
    "Siyosatshunoslikka kirish": ("Введение в политологию", "Introduction to Political Science"),
    "Qiyosiy siyosat": ("Сравнительная политология", "Comparative Politics"),
    "Siyosiy tahlil": ("Политический анализ", "Political Analysis"),
    "Siyosiy geografiya": ("Политическая география", "Political Geography"),
    "Geosiyosat": ("Геополитика", "Geopolitics"),
    "Diplomatiya": ("Дипломатия", "Diplomacy"),
    "Diplomatik protokol": ("Дипломатический протокол", "Diplomatic Protocol"),
    "Diplomatik protokol va etiket": ("Дипломатический протокол и этикет", "Diplomatic Protocol and Etiquette"),
    "Diplomatik va konsullik xizmati": ("Дипломатическая и консульская служба", "Diplomatic and Consular Service"),
    "Konsullik xizmati": ("Консульская служба", "Consular Service"),
    "Xalqaro muzokaralar": ("Международные переговоры", "International Negotiations"),
    "Xalqaro xavfsizlik": ("Международная безопасность", "International Security"),
    "Tashqi siyosat": ("Внешняя политика", "Foreign Policy"),
    "O'zbekiston tashqi siyosati": ("Внешняя политика Узбекистана", "Foreign Policy of Uzbekistan"),
    "O'zbekiston Respublikasining tashqi siyosati": ("Внешняя политика Республики Узбекистан",
                                                     "Foreign Policy of the Republic of Uzbekistan"),
    "Xorijiy mamlakatlar siyosiy tizimi": ("Политические системы зарубежных стран", "Political Systems of Foreign Countries"),
    "Markaziy Osiyo xalqaro munosabatlar tizimida": ("Центральная Азия в системе международных отношений",
                                                     "Central Asia in the System of International Relations"),
    "Barqaror rivojlanish maqsadlari": ("Цели устойчивого развития", "Sustainable Development Goals"),
    "Jahon adabiyoti": ("Мировая литература", "World Literature"),
    # --- huquq
    "Davlat va huquq nazariyasi": ("Теория государства и права", "Theory of State and Law"),
    "Konstitutsiyaviy huquq": ("Конституционное право", "Constitutional Law"),
    "Fuqarolik huquqi": ("Гражданское право", "Civil Law"),
    "Xalqaro ommaviy huquq": ("Международное публичное право", "Public International Law"),
    "Xalqaro xususiy huquq": ("Международное частное право", "Private International Law"),
    "Inson huquqlari": ("Права человека", "Human Rights"),
    "Diplomatik huquq": ("Дипломатическое право", "Diplomatic Law"),
    # --- iqtisodiyot
    "Iqtisodiyot nazariyasi": ("Экономическая теория", "Economic Theory"),
    "Iqtisodiy nazariya": ("Экономическая теория", "Economic Theory"),
    "Mikroiqtisodiyot": ("Микроэкономика", "Microeconomics"),
    "Makroiqtisodiyot": ("Макроэкономика", "Macroeconomics"),
    "Xalqaro iqtisodiyot": ("Международная экономика", "International Economics"),
    "Xalqaro savdo": ("Международная торговля", "International Trade"),
    "Xalqaro moliya": ("Международные финансы", "International Finance"),
    "Moliya": ("Финансы", "Finance"),
    "Marketing": ("Маркетинг", "Marketing"),
    "Buxgalteriya hisobi": ("Бухгалтерский учёт", "Accounting"),
    "Raqamli iqtisodiyot": ("Цифровая экономика", "Digital Economy"),
    "Statistika": ("Статистика", "Statistics"),
    "Ekonometrika": ("Эконометрика", "Econometrics"),
    # --- umumiy fanlar
    "Matematika": ("Математика", "Mathematics"),
    "Oliy matematika": ("Высшая математика", "Higher Mathematics"),
    "Tarix": ("История", "History"),
    "Jahon tarixi": ("Всемирная история", "World History"),
    "O'zbekistonning eng yangi tarixi": ("Новейшая история Узбекистана", "Contemporary History of Uzbekistan"),
    "O'zbekiston tarixi": ("История Узбекистана", "History of Uzbekistan"),
    "Falsafa": ("Философия", "Philosophy"),
    "Mantiq": ("Логика", "Logic"),
    "Sotsiologiya": ("Социология", "Sociology"),
    "Psixologiya": ("Психология", "Psychology"),
    "Madaniyatshunoslik": ("Культурология", "Cultural Studies"),
    "Dinshunoslik": ("Религиоведение", "Religious Studies"),
    "Ekologiya": ("Экология", "Ecology"),
    "Axborot texnologiyalari": ("Информационные технологии", "Information Technology"),
    "Axborot kommunikatsiya texnologiyalari": ("Информационно-коммуникационные технологии",
                                               "Information and Communication Technologies"),
    "Axborot xavfsizligi": ("Информационная безопасность", "Information Security"),
    "Jismoniy tarbiya": ("Физическая культура", "Physical Education"),
    "Jismoniy tarbiya va sport": ("Физическая культура и спорт", "Physical Education and Sport"),
    "Akademik yozuv": ("Академическое письмо", "Academic Writing"),
    "Ilmiy tadqiqot metodologiyasi": ("Методология научного исследования", "Research Methodology"),
    "Tadqiqot metodologiyasi": ("Методология исследования", "Research Methodology"),
    "Ritorika": ("Риторика", "Rhetoric"),
    "Nutq madaniyati": ("Культура речи", "Speech Culture"),
    "Kurs ishi": ("Курсовая работа", "Term Paper"),
    "Malakaviy amaliyot": ("Квалификационная практика", "Internship"),
    "Bitiruv malakaviy ishi": ("Выпускная квалификационная работа", "Graduation Thesis"),
    # --- tillar
    "Asosiy chet tili": ("Основной иностранный язык", "Primary Foreign Language"),
    "Ikkinchi chet tili": ("Второй иностранный язык", "Second Foreign Language"),
    "Chet tili": ("Иностранный язык", "Foreign Language"),
    "Xorijiy til": ("Иностранный язык", "Foreign Language"),
    "Ingliz tili": ("Английский язык", "English"),
    "Rus tili": ("Русский язык", "Russian"),
    "O'zbek tili": ("Узбекский язык", "Uzbek"),
    "Fransuz tili": ("Французский язык", "French"),
    "Nemis tili": ("Немецкий язык", "German"),
    "Ispan tili": ("Испанский язык", "Spanish"),
    "Italyan tili": ("Итальянский язык", "Italian"),
    "Italian tili": ("Итальянский язык", "Italian"),
    "Portugal tili": ("Португальский язык", "Portuguese"),
    "Arab tili": ("Арабский язык", "Arabic"),
    "Fors tili": ("Персидский язык", "Persian"),
    "Turk tili": ("Турецкий язык", "Turkish"),
    "Xitoy tili": ("Китайский язык", "Chinese"),
    "Yapon tili": ("Японский язык", "Japanese"),
    "Koreys tili": ("Корейский язык", "Korean"),
    "Hind tili": ("Хинди", "Hindi"),
    "Urdu tili": ("Урду", "Urdu"),
    "Tarjima nazariyasi": ("Теория перевода", "Translation Theory"),
    "Amaliy tarjima": ("Практический перевод", "Practical Translation"),
    # --- nazorat turlari
    "O'rtacha ball": ("Средний балл", "Average score"),
    "Joriy nazorat": ("Текущий контроль", "Continuous assessment"),
    "Oraliq nazorat": ("Промежуточный контроль", "Midterm assessment"),
    "Yakuniy nazorat": ("Итоговый контроль", "Final examination"),
    "Umumiy ball": ("Итоговый балл", "Total score"),
    "Umumiy": ("Итого", "Total"),
    "Jami": ("Итого", "Total"),
    # --- xonalar va boshqalar
    "Katta zal": ("Большой зал", "Main hall"),
    "Kompyuter xonasi": ("Компьютерный класс", "Computer room"),
    "Majlislar zali": ("Зал заседаний", "Conference hall"),
    "Sport zali": ("Спортивный зал", "Gym"),
    "Kutubxona": ("Библиотека", "Library"),
    "Kunduzgi": ("Очная", "Full-time"),
    "Sirtqi": ("Заочная", "Part-time"),
    "Bakalavr": ("Бакалавриат", "Bachelor's"),
    "Magistr": ("Магистратура", "Master's"),
}
